### ISSUE TITLE
Force DNS resolution

### ISSUE THREAD

**Issue by pompombidou** [binarysec/gate#37]
Hello,

 I have a website preproduction server working with Squid. (forward Proxy) I have to change server and I'm am looking for an easier and more lightweight solution.

Basic need is the website should have exactly the same URL on production and preproduction but on preproduction the user passes through a forward proxy (currently Squid). When a user goes through our proxy, the resolution of the DNS is forced to the IP of the preproduction server.

I use the host file option of squid (http://www.squid-cache.org/Doc/config/hosts_file/) where I dump all the domains with the IP of the preproduction server. (not brilliant but effective)

Is there a way to bypass GateJS DNS resolution and avoid DNS resolution by forcing DNS to IP 1.2.3.4 ?

I cannot change system host file.

Thanks a lot !

**Comment by mykiimike** [comment]
You are looking for a way to change /etc/hosts by /home/you/hosts ?

**Comment by pompombidou** [comment]
Not really. I'm trying to manually force the proxy that when it receives a forward request to mydomain.com (1.2.3.4) or mydomaine.org (2.3.4.5) or anydomain.net (3.4.5.6) not to resolve the DNS and probe the server to get the page but to get the page on 127.0.0.1.

**Comment by mykiimike** [comment]
Yup understood, actually if you place your domain into /etc/hosts it should work. Lazarus974 will make possible to change the host file in the configuration. If /etc/hosts doesn't then there is a problem :)

**Comment by pompombidou** [comment]
Change the host in the configuration would be brilliant.
I cannot change the system /etc/host file because some other services need to use the domain on the real IP.

**Comment by Lazarus974** [comment]
Hello,

Pull request https://github.com/binarysec/gate/pull/38 should fix this issue as soon as it is merged to the master branch.
You will simply have to add to your /etc/gatejs/config.js file :
```js
hostsFile: "/etc/gatejs/hosts"
```
Replace with whatever path you need.
The whole file should look like this :
```js
var serverConfig = function(bs) { return({
	serverProcess: 4,
	hostname: "testServer0",
	runDir: "/var/run/gatejs",
	dataDir: "/home/gatejs-data",
	logDir: "/var/log/gatejs",
	confDir: '/etc/gatejs',
	hostsFile: "/etc/gatejs/hosts",
	http: { ... },
	pipeline: { ... }
})};
```

**Comment by pompombidou** [comment]
Thanks a lot ! Quite impressed by your reactivity !!!!

**Comment by mykiimike** [comment]
Merged. Thanks ! Star it ;)
