### ISSUE TITLE
HTTPS Forward Proxy - Timeout

### ISSUE THREAD

**Issue by jcxeon** [binarysec/gate#39]
Hello,

When I setup a https forward proxy with ssl true to proxyPass opcode.  The socket just seems to timeout.  Pipeline resolved = false when it happens.  Not sure how to troubleshoot further.  The http version forward proxy works perfectly.

 curl -v -x https://proxy:8081 https://www.google.com

```javascript
http: {
                forwardInterfaceSecure: {
                        type: 'forward',
                        port: 8081,
                        pipeline: 'forwardSecure',
                        ssl: true,
                        cert: 'cert',
                        key: 'key',
                }
        },

pipeline: {
forwardSecure: [
            ['proxyPass', {
                mode: 'host',
                timeout: 15,
                allowConnect: true,
            }]
        ],
},
```

**Comment by mykiimike** [comment]
Hi,

Thank you for the feedback. Could you try the pipeline forwardSecure into a non SSL interface. 
I'm not sure whether it is possible to initiate a CONNECT trough SSL interface.

mykii-

**Comment by mykiimike** [comment]
Actually i checked the code and obviously it supports allowConnect both on SSL and non SSL interface. However it is possible that the client doesn't support this way because it must handle 2 BIOs contexts at the same time with one "virtualized"

**Comment by Dagrut** [comment]
I checked it too, and my curl version (curl 7.26.0 (x86_64-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3) is sending a plain text CONNECT, without encryption.
Inside gate, the only event called when I send a request is .on('connection') (http/js/forward.js:318), and then I think it is not able to process the request (with or without the allowConnect option). The .on('error') is not called too, which might be a bug inside node.js.

Also, the allowConnect option have to be placed in the interface, not in the proxyPass pipeline option :wink:

**Comment by jcxeon** [comment]
Thank you for the replies.  I tried with ssl false and true, still same thing.  But it looks like @Dagrut is onto something. Using curl is a good test, but I also tried Firefox and Chrome proxy settings to test as well.

I moved the allowConnect option to the interface, no wonder it never hit that code :smile:

**Comment by mykiimike** [comment]
@jcxeon does it work with the allowConnect at the right place ? and with SSL off ?

**Comment by jcxeon** [comment]
@mykiimike Yes, it does work with the below configuration.  Would having SSL on, on a forward proxy offer any additional security?  Since the CONNECT just tunnels the traffic without any inspection.
```javascript
http: {
                forwardInterfaceSecure: {
                        type: 'forward',
                        port: 8081,
                        pipeline: 'forwardSecure',
                        ssl: false,
                        cert: 'cert',
                        key: 'key',
                        allowConnect: true,
                }
        },

pipeline: {
forwardSecure: [
            ['proxyPass', {
                mode: 'host',
                timeout: 15,
            }]
        ],
},
```

allowConnect in this doc is incorrect then?
https://github.com/binarysec/gate/wiki/OpcodeForwardProxyPass

**Comment by mykiimike** [comment]
The good link is http://gatejs.org/index.php//documentation/1-5/http-forward.html
We have to remove the link you pasted.
As soon as your client support SSLinSSL tunneling it will works. The design for HTTP and HTTPS is the same then theoretically it should work on both case.
As @Dagrut said the CONNECT is sent w/o encryption and so SSL will drop the connection.

**Comment by jcxeon** [comment]
Thank you @mykiimike and @Dagrut that all makes perfect sense.
