### ISSUE TITLE
Restart fails on Debian Jessie x64

### ISSUE THREAD

**Issue by mykiimike** [binarysec/gate#42]
Restarting gate with init.d script doesn't stops the running processes. 
* 2 HTTP interface reverse with SSL
* 1 reverse website

**Comment by Dagrut** [comment]
That works for me.
How was gatejs installed? (arguments of ./configure?)

**Comment by mykiimike** [comment]
Right point. It has been installed in a special prefix dir ! ./configure --prefix=/something

**Comment by Dagrut** [comment]
Did you copy `/something/etc/init.d/gatejs` to `/etc/init.d/gatejs`?

**Comment by mykiimike** [comment]
yup

**Comment by Dagrut** [comment]
Is the PID in `/something/var/run/gatejs/master.pid` the right one? If it's not, try : 
```sh
kill $(ps auxf | grep 'gate.js Master' | grep -v 'grep' | awk '{ print $2 }')
/etc/init.d/gatejs start
```
And check again.

**Comment by mykiimike** [comment]
OK i think we have to change the way to restart the service..

**Comment by Dagrut** [comment]
In which way?
Whatever I do, it still works for me.
