### ISSUE TITLE
linux/if.h 

### ISSUE THREAD

**Issue by tajinder2001** [binarysec/gate#44]
HI

When trying to install on OS X 10.10.5 i keep getting the message that it cannot find file Linux/if.h

Can anyone provide any assistance on getting the install done?

Thanks

**Comment by tajinder2001** [comment]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.12.7 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/share/gatejs/node/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tajinderchana/gate/src/lib/tproxy/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/share/gatejs/node/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/tajinderchana/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/tajinderchana/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/share/gatejs/node/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/tajinderchana/gate/src/lib/tproxy',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/tproxy/src/tproxy.o
In file included from ../src/tproxy.cc:21:
../src/module.hh:38:10: fatal error: 'linux/if.h' file not found
#include <linux/if.h>
         ^
1 error generated.
make[2]: *** [Release/obj.target/tproxy/src/tproxy.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/gatejs/node/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/share/gatejs/node/bin/node-gyp" "clean" "configure" "build"
gyp ERR! cwd /Users/tajinderchana/gate/src/lib/tproxy
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
make[1]: *** [rebuild] Error 1
make: *** [install] Error 2

**Comment by tajinder2001** [comment]
Thats what i get when the error is happening

**Comment by mykiimike** [comment]
Thank you very much for the details. Actually the problem comes with the TPROXY support. We will fix this very soon.
MV

**Comment by Dagrut** [comment]
Hi!

It should work now ( https://travis-ci.org/binarysec/binarysec/gate/jobs/86775181 ).

Have a nice day!

**Comment by tajinder2001** [comment]
HI Thanks for looking into this for me 

I will try to reinstall and post back any results

**Comment by tajinder2001** [comment]
This is what i am now seeing:

/etc/init.d/gatejs: line 30: ulimit: open files: cannot modify limit: Invalid argument
/etc/init.d/gatejs: line 37: /lib/init/vars.sh: No such file or directory
