### ISSUE TITLE
Error when starting Gate JS 

### ISSUE THREAD

**Issue by tajinder2001** [binarysec/gate#45]
I am seeing the following error in the terminal window when trying to start Gate JS

/etc/init.d/gatejs: line 30: ulimit: open files: cannot modify limit: Invalid argument
/etc/init.d/gatejs: line 37: /lib/init/vars.sh: No such file or directory

(Edit by @Dagrut: Follow-up of #44 ).

**Comment by Dagrut** [comment]
I just looked around for it, and it seems that init.d files should not be used on MacOS, but .plist files with launchctl. I'll see what I can do about it. For now, you can still manage gatejs with :
```sh
# Start :
/usr/local/share/gatejs/node/bin/node /usr/local/share/gatejs/service.js --config=/etc/gatejs/config.js
# Reload :
/usr/local/share/gatejs/node/bin/node /usr/local/share/gatejs/controler.js --socket=/var/run/gatejs/ipc send LFW system:graceful
# Logrotate
/usr/local/share/gatejs/node/bin/node /usr/local/share/gatejs/controler.js --socket=/var/run/gatejs/ipc send LFW core:logger:reload
# Stop
kill $(cat /var/run/gatejs/master.pid)
```

Adjust the path with your `./configure` settings.

**Comment by tajinder2001** [comment]
Hi Was this resolved as this has been closed?

**Comment by Dagrut** [comment]
Yes. To start and stop gatejs on MacOS, you should now use : 
apachectl start com.gatejs.daemon
apachectl stop com.gatejs.daemon
