### ISSUE TITLE
Bug using forever and gatejs

### ISSUE THREAD

**Issue by mykiimike** [binarysec/gate#54]

**Comment by mykiimike** [comment]
No working:

```bash
forever -a -o /var/log/gatejs/forever.log -e /var/log/gatejs/forever-error.log start --uid gatejs --max_old_space_size=500 /usr/bin/gatejs --config=/etc/gatejs/config.js
```

I think the problem comes from the bash header into service.js #!/bin/bash

**Comment by Dagrut** [comment]
This should be `#!/usr/bin/nodejs` and not `#!/bin/bash`.
It works for me. What does `/var/log/gatejs/forever-error.log` say?

**Comment by mykiimike** [comment]
@Dagrut where did you see **#!/bin/bash** ?

**Comment by Dagrut** [comment]
Well, you said : 
> I think the problem comes from the bash header into service.js #!/bin/bash
An other problem may be the file access (are the configuration files readable? Ssl certificates?). Or maybe it's listening on a port < 1024 without proper permissions?

**Comment by mykiimike** [comment]
OK problem solved
