### ISSUE TITLE
[Request] Add support for letsencrypt certbot 

### ISSUE THREAD

**Issue by mrudelle** [binarysec/gate#57]
Either an opcode that serves static files (eg to serve /var/www/.well-known/acme-challenge) or more intertwined integration with certbot for automatic renewal.

**Comment by Dagrut** [comment]
I added an opcode which can handle this (commit fd1dd81145b4d58103ad06e8cefc3bf3ce74d7aa ) : 
```js
		{ 
			name: 'fsAccess',
			regex: /^\/fs/,
			pipeline: [
				['fileSystem', '/tmp'],
			]
		},
```
It will run a `.replace(/^\/fs/, '/tmp');` on the url, and then get the corresponding file (the path cannot go out of /tmp here, even with `../`. On error or when a file is not found, a 404 is sent. You also have two options, which default as : 
```js
['fileSystem', '/tmp', {
    maxAge: 86400,
    skipErrors: false,
}],
```
maxAge is the maximum age of the file (Cache-Control header), and skipErrors tells to return 404 or to skip it and go to the next opcode on error.
Using --webroot with certbot should now work with it.
